### ISSUE TITLE
Error:(21, 8) error: MockLocalLibraryManager

### ISSUE THREAD

**Issue by HenryChigbo** [MichaelObi/PaperPlayer#10]
Error:(21, 8) error: MockLocalLibraryManager is not abstract and does not override abstract method getAlbum(long) in LibraryManager

**Comment by MichaelObi** [comment]
Hey @HenryChigbo. I've gone through this and there was an issue. I didn't update the mock library manager used for running tests. It'll get fixed. 
To build the project for use, you have to change the build flavor from `MockDebug` to `ProdDebug`. It'll use the actual library manager for production.
I want to use this opportunity to make sure all Unit tests are running correctly too. This may take a few days. But switching to a production build flavor should allow you to run the project.

Thanks for pointing this out

**Comment by MichaelObi** [comment]
The issue has been taken care of.
