### ISSUE TITLE
Logo Proposal for Paper Player

### ISSUE THREAD

**Issue by mendezand** [MichaelObi/PaperPlayer#17]
Hi.
In view of the fact that the app does not have a defined logo yet, I decided to contribute with the project in the design area.
I have created two logo options that can be used in the application and fits perfectly in mobile applications.

Any type of modification not hesitate to tell me.
![preview](https://user-images.githubusercontent.com/38763253/39377809-7baa9712-4a24-11e8-88bc-92e528991f32.PNG)

**Comment by MichaelObi** [comment]
Thanks a lot for this @mendezand 
I think the second sets look like cassette tapes and would be better.
I'd like to defer choice of color to you though.
Also, the lip on the bottom left may not play well with Android adaptive launcher icons as the background will be defined by the Launcher or system

**Comment by mendezand** [comment]
@MichaelObi You're right, what color do you prefer for Paper Player?
I will make pertinenten modifications to be adapted to the android system.

**Comment by MichaelObi** [comment]
I think the red or yellow would work great.
If you're done, I'll need the vector files to complete the swap.

**Comment by mendezand** [comment]
@MichaelObi  
![image](https://user-images.githubusercontent.com/38763253/39502267-428d972e-4d8d-11e8-9dc8-efcac9cf26a1.png)
 I added a small shadow detail and I used the color yellow as the principal.
If you want additional detail not forget to tell me.

**Comment by mendezand** [comment]
Hi Michael, how are you? let me know if you need a change in the logo or
even a larger modification. I will be attentive to your comments. Greetings.

**Comment by MichaelObi** [comment]
Thanks for reaching out. I'm sorry I've been really busy. Can you send me the raw vector file, so I can separate the foreground and background and then resize it for different screens.

**Comment by mendezand** [comment]
![android icon](https://user-images.githubusercontent.com/38763253/39664542-bc68f2ec-5052-11e8-911c-0f1541e1bcb2.png)
![app icon](https://user-images.githubusercontent.com/38763253/39664543-bc8c9be8-5052-11e8-8725-d734fd714661.png)

I have increased them in size so you can perform your tests.

**Comment by mendezand** [comment]
I attach editable files of the final modifications.
![image](https://user-images.githubusercontent.com/38763253/39824294-fc9f41ea-537c-11e8-883f-ae2754e451bf.png)

[Icon Design Files](https://drive.google.com/open?id=1Cw-Hi1VcLwirZX38llNGiNsy3xqu46mC)

**Comment by MichaelObi** [comment]
Thanks.

Can you send SVGs instead?

Michael Obi

**Comment by mendezand** [comment]
Yes sir.

**Comment by mendezand** [comment]
I realized that there were some errors in the files, including SVG. I've fixed them.

[Files Fixed](https://drive.google.com/open?id=1EANYW2GwPmxZu4LqJ8pVFR_XswavtfCf)

**Comment by MichaelObi** [comment]
I made the change. This is the new launcher icon. Thanks a lot Ander. I also put your name under contributors in the Readme file.

I'll be closing this now.
